# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "Sam Alderfer"
description: > # this means to ignore newlines until "email:"
   The thoughts and writings of Sam Alderfer

email: sam@samalderfer.com
#blog logo
logo: "/assets/images/sa_logo.png"
# blog cover
cover: "/assets/images/cover.jpg"

name: 'Sam Alderfer'
author: 'Sam Alderfer'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://samalderfer.com" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/salderfer
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://facebook.com/salderfe
    desc: Connect with me facebook
    share_url: //www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon: instagram
    url:  https://instagram.com/smaldi631
    desc: Follow me on instagram

#  - icon:	github
#    url:	https://github.com/dirkfabisch
#    desc:	Fork me on github
#    share_url:
#    share_title:
#    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
